server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  - targets:
      - localhost
    labels:
      job: python_logs
      __path__: /var/log/python_logs/*log
  pipeline_stages:
      - json:
          expressions:
            system: system
            cpu: cpu
            log_level: log_level
            log_message: log_message
      - labels:
          system: ""
          cpu: ""
          log_level: ""
          log_message: ""
